-- El catálogo se movió a supabase/migrations/20260706000005_catalog.sql
-- (así viaja a producción con `supabase db push`).
-- Los datos de DEMO (usuarios de prueba, batalla PK) están en scripts/seed-dev.mjs.
